version: "3.7"
services:
  # Layanan Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mirzarama27/simlitabmas-app:latest
    container_name: nextjs_app
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}:${MINIO_PORT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db
      - minio
    networks:
      - simlitabmas_network
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy & npx prisma studio & npm run dev"

  # Layanan PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - simlitabmas_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Layanan MinIO
  minio:
    image: minio/minio
    container_name: minio_storage
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - simlitabmas_network
    command: server /data --console-address ":9001"

volumes:
  pgdata:
  miniodata:

networks:
  simlitabmas_network:
