// This file was auto-generated by prisma-generator-typescript-interfaces

export type user_type = "ketua_rg" | "kaprodi" | "lecturer" | "admin";

export type config_type = "system" | "user" | "proposal";

export type proposal_suggestion_status = "menunggu_proposal" | "menunggu_rg" | "menunggu_kaprodi" | "menunggu_admin" | "menunggu_review" | "menunggu_revisi" | "menunggu_laporan" | "tersimpan" | "menunggu" | "ditolak" | "diterima" | "selesai";

export type degree = "S1" | "S2" | "S3";

export type evaluation_phase = "evaluasi_proposal" | "evaluasi_monev" | "evaluasi_akhir";

export type proposal_suggestion_phase = "pengajuan" | "evaluasi_proposal" | "penetapan" | "monev" | "evaluasi_akhir" | "penetapan_akhir";

export interface config {
  id: number;
  name: string | null;
  value: JsonValue | null;
  file: string | null;
  default: boolean | null;
  config_type: config_type | null;
}

export interface user {
  id: number;
  name: string | null;
  user_type: user_type | null;
  password: string | null;
  username: string | null;
  email: string | null;
  lecturer_id: number | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  log?: log[];
  user_profile?: user_profile | null;
  lecturer?: lecturer | null;
  refresh_token?: refresh_token | null;
}

export interface refresh_token {
  id: number;
  token: string;
  user_id: number;
  user?: user | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
}

export interface user_profile {
  id: number;
  user_id: number;
  lecturer_id: number;
  bio: string | null;
  gender: string | null;
  profile_pic: string | null;
  createdAt: Date;
  updatedAt: Date;
  user?: user | null;
  lecturer?: lecturer | null;
}

export interface lecturer {
  id: number;
  name: string;
  research_group_id: number | null;
  department_id: number | null;
  nidn: string | null;
  nip: string | null;
  degree: JsonValue | null;
  is_ketua_rg: boolean | null;
  is_kaprodi: boolean | null;
  highest_degree: degree | null;
  position_id: number | null;
  signature_url: string | null;
  phone_number: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  research_group?: research_group | null;
  department?: department | null;
  position?: position | null;
  user?: user[];
  proposal_suggestion?: proposal_suggestion[];
  lecturer_member?: lecturer_member[];
  reviewer?: reviewer[];
  user_profile?: user_profile | null;
}

export interface reviewer {
  id: number;
  lecturer_id: number;
  category: string;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  lecturer?: lecturer | null;
  review?: review[];
}

export interface research_group {
  id: number;
  name: string;
  description: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  lecturer?: lecturer[];
  proposal_suggestion?: proposal_suggestion[];
  lecturer_member?: lecturer_member[];
}

export interface department {
  id: number;
  name: string;
  description: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  lecturer?: lecturer[];
  proposal_suggestion?: proposal_suggestion[];
  student_member?: student_member[];
  lecturer_member?: lecturer_member[];
}

export interface year_research {
  id: number;
  year: number;
  open_date: Date;
  closed_date: Date;
  is_active: boolean;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  proposal_suggestion?: proposal_suggestion[];
  configuration?: configuration | null;
}

export interface position {
  id: number;
  name: string;
  description: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  lecturer?: lecturer[];
  position_schema?: position_schema[];
  lecturer_member?: lecturer_member[];
}

export interface position_schema {
  id: number;
  schema_id: number;
  position_id: number;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  schema?: schema | null;
  position?: position | null;
}

export interface schema {
  id: number;
  name: string;
  description: string | null;
  type: string | null;
  max_cost: Decimal | null;
  min_degree: degree | null;
  is_student: boolean | null;
  is_partner: boolean | null;
  is_lecturer: boolean | null;
  is_active: boolean;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  position_schema?: position_schema[];
  proposal_suggestion?: proposal_suggestion[];
  cost_category?: cost_category[];
  external_document_category?: external_document_category[];
}

export interface proposal_suggestion {
  id: number;
  name: string;
  year_research_id: number | null;
  schema_id: number | null;
  lecturer_id: number | null;
  research_group_id: number | null;
  department_id: number | null;
  phase: proposal_suggestion_phase | null;
  status: proposal_suggestion_status | null;
  open: boolean;
  is_active: boolean | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  year_research?: year_research | null;
  schema?: schema | null;
  lecturer?: lecturer | null;
  research_group?: research_group | null;
  department?: department | null;
  lecturer_member?: lecturer_member[];
  student_member?: student_member[];
  vendor_member?: vendor_member[];
  suggestion_cost?: suggestion_cost[];
  additional_document?: additional_document[];
  external_document?: external_document[];
  logbook?: logbook[];
  proposal?: proposal | null;
  final_report?: final_report[];
  evaluation?: evaluation[];
}

export interface proposal {
  id: number;
  proposal_suggestion_id: number;
  name: string | null;
  abstract: string | null;
  keyword: string | null;
  background: string | null;
  purpose: string | null;
  method: string | null;
  literature_review: string | null;
  bibliography: string | null;
  file_url: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  suggestion?: proposal_suggestion;
}

export interface lecturer_member {
  id: number;
  proposal_suggestion_id: number;
  lecturer_id: number;
  name: string | null;
  research_group_id: number | null;
  department_id: number | null;
  nip: string | null;
  degree: JsonValue | null;
  is_ketua_rg: boolean | null;
  position_id: number | null;
  signature_url: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  proposal_suggestion?: proposal_suggestion;
  lecturer?: lecturer;
  department?: department | null;
  research_group?: research_group | null;
  position?: position | null;
}

export interface student_member {
  id: number;
  proposal_suggestion_id: number;
  name: string;
  nrp: string;
  department_id: number;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  proposal_suggestion?: proposal_suggestion;
  department?: department;
}

export interface vendor_member {
  id: number;
  proposal_suggestion_id: number;
  name: string;
  description: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  proposal_suggestion?: proposal_suggestion;
}

export interface suggestion_cost {
  id: number;
  name: string;
  proposal_suggestion_id: number;
  cost_category_id: number;
  total: number | null;
  description: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  proposal_suggestion?: proposal_suggestion;
  cost_category?: cost_category;
}

export interface cost_category {
  id: number;
  schema_id: number;
  name: string;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  schema?: schema;
  suggestion_cost?: suggestion_cost[];
}

export interface additional_document {
  id: number;
  proposal_suggestion_id: number;
  name: string;
  content: string | null;
  file_url: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  proposal_suggestion?: proposal_suggestion;
}

export interface logbook {
  id: number;
  proposal_suggestion_id: number;
  name: string | null;
  description: string | null;
  file_url: string | null;
  progress: number | null;
  phase: proposal_suggestion_phase | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  proposal_suggestion?: proposal_suggestion;
}

export interface final_report {
  id: number;
  proposal_suggestion_id: number;
  name: string | null;
  description: string | null;
  file_url: string | null;
  phase: proposal_suggestion_phase | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  proposal_suggestion?: proposal_suggestion;
}

export interface external_document {
  id: number;
  name: string;
  proposal_suggestion_id: number;
  category_name: string | null;
  status: string | null;
  description: string | null;
  file_url: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  proposal_suggestion?: proposal_suggestion;
}

export interface log {
  id: number;
  table: string;
  audit: string | null;
  user_id: number | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  user?: user | null;
}

export interface evaluation {
  id: number;
  proposal_suggestion_id: number | null;
  evaluation_phase: evaluation_phase | null;
  category: string | null;
  status: proposal_suggestion_status | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  proposal_suggestion?: proposal_suggestion | null;
  review?: review[];
}

export interface review {
  id: number;
  evaluation_id: number;
  reviewer_id: number;
  note: string | null;
  average_score: number | null;
  status: proposal_suggestion_status | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  evaluation?: evaluation;
  reviewer?: reviewer;
  criterion_score?: criterion_score[];
}

export interface criterion {
  id: number;
  name: string;
  category: string | null;
  phase: evaluation_phase;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  criterion_score?: criterion_score[];
}

export interface criterion_score {
  id: number;
  criterion_id: number;
  review_id: number;
  score: number;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  criterion?: criterion;
  review?: review;
}

export interface external_document_category {
  id: number;
  schema_id: number;
  name: string;
  description: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  schema?: schema;
}

export interface configuration {
  id: number;
  year_research_id: number | null;
  createdAt: Date;
  updatedAt: Date;
  year_research?: year_research | null;
}

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;

type Decimal = { valueOf(): string };
